import {NgModule} from '@angular/core';
import {
  MatTableModule,
  MatToolbarModule,
  MatPaginatorModule,
  MatIconModule,
  MatButtonModule,
  MatSortModule,
  MatFormFieldModule,
  MatInputModule,
  MatCardModule,
  MatSnackBarModule,
  MatSidenavModule,
  MatMenuModule,
  MatDividerModule,
  MatDialogModule,
  MatSelectModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MAT_DATE_LOCALE,
  MatExpansionModule,
  MatAutocompleteModule,
  MatProgressBarModule,
  MatStepperModule,
  MatBottomSheetModule,
  MatGridListModule,
  MatButtonToggleModule,
  MatProgressSpinnerModule,
  MatCheckboxModule,
  MatListModule,
  MatBadgeModule,
  MatTabsModule, MatPaginatorIntl,
  MatChipsModule, MatTooltipModule,
  MatSlideToggleModule
} from '@angular/material';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {getEspPaginatorIntl} from '../helpers/esp-paginator-intl';
import {DragDropModule} from '@angular/cdk/drag-drop';

@NgModule({
  imports: [
    BrowserAnimationsModule,
    MatTableModule,
    MatToolbarModule,
    MatTooltipModule,
    MatPaginatorModule,
    MatIconModule,
    MatButtonModule,
    MatSortModule,
    MatFormFieldModule,
    MatInputModule,
    MatCardModule,
    MatSnackBarModule,
    MatSidenavModule,
    MatMenuModule,
    MatDividerModule,
    MatDialogModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatExpansionModule,
    MatAutocompleteModule,
    MatProgressBarModule,
    MatStepperModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatListModule,
    MatBadgeModule,
    MatTabsModule,
    MatChipsModule,
    DragDropModule,
    MatSlideToggleModule
  ],
  exports: [
    MatTableModule,
    MatToolbarModule,
    MatTooltipModule,
    MatPaginatorModule,
    MatIconModule,
    MatButtonModule,
    MatSortModule,
    MatFormFieldModule,
    MatInputModule,
    MatCardModule,
    MatSnackBarModule,
    MatSidenavModule,
    MatMenuModule,
    MatDividerModule,
    MatDialogModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatExpansionModule,
    MatAutocompleteModule,
    MatProgressBarModule,
    MatStepperModule,
    MatBottomSheetModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatListModule,
    MatBadgeModule,
    MatTabsModule,
    MatChipsModule,
    DragDropModule,
    MatSlideToggleModule
  ],
  providers: [
    { provide: MAT_DATE_LOCALE, useValue: 'es-ES' },
    { provide: MatPaginatorIntl, useValue: getEspPaginatorIntl() }
  ],
  declarations: []
})
export class AppMaterialModule { }
